alias ealiases='vim ~/.oh-my-zsh/custom/aliases.zsh'
alias ea='vim ~/.config/awesome/rc.lua'
alias open='xdg-open'
alias o='xdg-open'
alias cl='clear'
alias saywhat='whatis "$(fc -nl -1 | awk "{print \$NF}")"'
alias info='info --vi-keys'
alias vim='nvim'
