#!/usr/bin/env bash

SERVICE_NAME='openvpn-client'
WILDCARD='@*'
SERVICE=$SERVICE_NAME$WILDCARD
# Get the first unit with data
UNIT="$(systemctl list-units -all ${SERVICE} | tail -n +2 | head -n1)"

# Get first service
service=$(echo $UNIT | cut -f1 -d ' ')
# Get state of service
state=$(echo $UNIT | cut -f3 -d ' ')

# Get the name of the VPN configuration
regexp='s/'${SERVICE_NAME}'@\(.*\).service/\1/'
name=$(echo $service | sed -e ${regexp})

# Echo depending on the result
if [ $state = "active" ]; then
    echo " $name"
    echo " $name"
    echo '#30FF30'
else
    echo " Down"
    echo " Down"
    echo '#468bcb'
fi
