#!/usr/bin/env bash
#xrandr --output eDP1 --off --output HDMI1 --scale 1.5x1.5 --panning 3840x2160+0+0 --output DP2 --right-of HDMI1 --panning 3840x2160+3840+0

xrandr --output eDP1 --off --output DP2 --panning 3840x2160+0+0 --output HDMI1 --right-of DP2 --panning 3840x2160+3840+0 --scale 1.5x1.5

# xrandr --output eDP1 --off --output DP2 --panning 3840x2160+0+0 --output HDMI1 --right-of DP2 --scale 1.5x1.5 --rotate right
